# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -r requirements.txt
      - name: Install app package
        run: |
          python -m pip install .
      - name: Test with pytest
        run: |
          # make sure we use the pip-installed package for tests
          mv any_app any_app_temp
          pytest
          mv any_app_temp any_app

  build-exe-windows:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -r requirements.txt
      - name: Install app package
        run: |
          python -m pip install .
      - name: Build executable
        shell: pwsh
        run: |
          ./build.ps1
      - name: List files to help debugging
        run: |
          ls dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/any_app-*.zip